<?php

namespace Eril\Migraw\Squash\Dumper;

use PDO;

final class PostgresSchemaDumper implements SchemaDriverDumper
{
    protected array $foreignKeys = [];

    public function __construct(
        protected PDO $pdo,
        protected string $migrationTable = 'migrations'
    ) {}

    public function dump(): array
    {
        $tables = $this->pdo->query(<<<'SQL'
SELECT c.relname
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind = 'r'
  AND n.nspname = current_schema()
ORDER BY c.relname
SQL)->fetchAll(PDO::FETCH_COLUMN);

        $schema = [];

        foreach ($tables as $table) {
            if ($table === $this->migrationTable) {
                continue;
            }

            $schema[$table] = [
                $this->createTable($table),
            ];

            foreach ($this->indexes($table) as $index) {
                $schema[$table][] = $index;
            }

            foreach ($this->foreignKeys($table) as $foreign) {
                $this->foreignKeys[] = $foreign;
            }
        }

        return $schema;
    }

    protected function createTable(string $table): string
    {
        $stmt = $this->pdo->prepare(<<<'SQL'
SELECT
    a.attname AS name,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS type,
    a.attnotnull AS not_null,
    a.attidentity AS identity,
    pg_get_expr(ad.adbin, ad.adrelid) AS default_value
FROM pg_attribute a
JOIN pg_class c ON c.oid = a.attrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_attrdef ad
    ON ad.adrelid = a.attrelid
   AND ad.adnum = a.attnum
WHERE c.relname = :table
  AND n.nspname = current_schema()
  AND a.attnum > 0
  AND NOT a.attisdropped
ORDER BY a.attnum
SQL);

        $stmt->execute(['table' => $table]);

        $definitions = [];

        foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $column) {
            $definition = $this->quote($column['name'])
                . ' '
                . $column['type'];

            if ($column['identity'] === 'a') {
                $definition .= ' GENERATED ALWAYS AS IDENTITY';
            } elseif ($column['identity'] === 'd') {
                $definition .= ' GENERATED BY DEFAULT AS IDENTITY';
            } elseif ($column['default_value'] !== null) {
                $definition .= ' DEFAULT ' . $column['default_value'];
            }

            if ($column['not_null']) {
                $definition .= ' NOT NULL';
            }

            $definitions[] = $definition;
        }

        $stmt = $this->pdo->prepare(<<<'SQL'
SELECT
    conname,
    pg_get_constraintdef(oid, true) AS definition
FROM pg_constraint
WHERE conrelid = (
    SELECT c.oid
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = :table
      AND n.nspname = current_schema()
)
AND contype IN ('p', 'u', 'c', 'x')
ORDER BY conname
SQL);

        $stmt->execute(['table' => $table]);

        foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $constraint) {
            $definitions[] =
                'CONSTRAINT '
                . $this->quote($constraint['conname'])
                . ' '
                . $constraint['definition'];
        }

        return sprintf(
            "CREATE TABLE %s (\n    %s\n);",
            $this->quote($table),
            implode(",\n    ", $definitions)
        );
    }

    protected function indexes(string $table): array
    {
        $stmt = $this->pdo->prepare(<<<'SQL'
SELECT pg_get_indexdef(i.indexrelid)
FROM pg_index i
JOIN pg_class t ON t.oid = i.indrelid
JOIN pg_namespace n ON n.oid = t.relnamespace
LEFT JOIN pg_constraint c ON c.conindid = i.indexrelid
WHERE t.relname = :table
  AND n.nspname = current_schema()
  AND c.oid IS NULL
ORDER BY i.indexrelid
SQL);

        $stmt->execute(['table' => $table]);

        return array_map(
            static fn(string $sql): string => rtrim($sql, ';') . ';',
            $stmt->fetchAll(PDO::FETCH_COLUMN)
        );
    }

    protected function foreignKeys(string $table): array
    {
        $stmt = $this->pdo->prepare(<<<'SQL'
SELECT
    conname,
    pg_get_constraintdef(oid, true) AS definition
FROM pg_constraint
WHERE conrelid = (
    SELECT c.oid
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = :table
      AND n.nspname = current_schema()
)
AND contype = 'f'
ORDER BY conname
SQL);

        $stmt->execute(['table' => $table]);

        $foreignKeys = [];

        foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $constraint) {
            $foreignKeys[] = sprintf(
                'ALTER TABLE %s ADD CONSTRAINT %s %s;',
                $this->quote($table),
                $this->quote($constraint['conname']),
                $constraint['definition']
            );
        }

        return $foreignKeys;
    }

    public function beforeCreate(): array
    {
        return [];
    }

    public function afterCreate(): array
    {
        return $this->foreignKeys;
    }

    public function beforeDrop(): array
    {
        return [];
    }

    public function afterDrop(): array
    {
        return [];
    }

    public function dropTable(string $table): string
    {
        return 'DROP TABLE IF EXISTS '
            . $this->quote($table)
            . ' CASCADE;';
    }

    protected function quote(string $name): string
    {
        return '"' . str_replace('"', '""', $name) . '"';
    }
}