<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Bootstrap File
    |--------------------------------------------------------------------------
    |
    | Optional bootstrap file loaded before Migraw resolves the database
    | connection. Useful when the application needs to initialize environment
    | variables, containers, helpers, or its own database layer.
    |
    */

    // 'bootstrap' => 'bootstrap.php',

    /*
    |--------------------------------------------------------------------------
    | Migration Preferences
    |--------------------------------------------------------------------------
    |
    | "path" defines where migration files are stored.
    |
    | "template" defines the default template generated by the make command.
    | Supported values: raw, fluent.
    |
    */

    'path' => 'database/migrations',

    'template' => 'raw',

    /*
    |--------------------------------------------------------------------------
    | Database Connection
    |--------------------------------------------------------------------------
    |
    | The connection may be defined using a configuration array, as shown
    | below.
    |
    | Migraw also accepts:
    |
    | - a PDO instance;
    | - a Closure or callable returning PDO;
    | - a Closure or callable returning a supported connection object;
    | - an object exposing getPdo() or pdo().
    |
    | Examples:
    |
    | 'connection' => new PDO(...),
    | 'connection' => static fn (): PDO => Database::connection(),
    | 'connection' => [Database::class, 'connection'],
    |
    | Only the fields required by the selected driver are used. This allows
    | the same configuration structure to be kept when switching between
    | MySQL, MariaDB, PostgreSQL, and SQLite.
    |
    */

    'connection' => [
        'driver' => $_ENV['DB_CONNECTION'] ?? 'sqlite',

        'host' => $_ENV['DB_HOST'] ?? '127.0.0.1',
        'port' => $_ENV['DB_PORT'] ?? '3306',
        'database' => $_ENV['DB_DATABASE'] ?? '',
        'username' => $_ENV['DB_USERNAME'] ?? 'root',
        'password' => $_ENV['DB_PASSWORD'] ?? '',
        'charset' => $_ENV['DB_CHARSET'] ?? 'utf8mb4',

        'sqlite_path' => 'database/production.sqlite',
    ],

];
